FROM node:12.18.0

ARG NODE_ENV

COPY ./front /home/front

WORKDIR /home/front

# Note: we npm install in prod because build tools are dev dependencies
CMD (which yarn || npm i -g yarn@1.15.2) && \
    if [ "$NODE_ENV" = "production" ] || [ "$NODE_ENV" = "recette" ]; then \
        echo "prod/recette"; \
        yarn install --production && \
        yarn run build && \
        cp -RT build dist; \
    else \
        echo "local"; \
        yarn && \
        yarn start; \
    fi
