FROM node:12.18.4

COPY ./api /home/api
WORKDIR /home/api

CMD (which yarn || npm i -g yarn@1.15.2) && \
    echo "$NODE_ENV"; \
    yarn install && \
    if [ "$NODE_ENV" = "production" ] || [ "$NODE_ENV" = "recette" ] || [ "$NODE_ENV" = "test" ]; then \
        yarn build:production && \ 
	    yarn start:production; \
    else \
        yarn start; \
    fi
