FROM node:12.18.0

ARG NODE_ENV
RUN echo $NODE_ENV

COPY ./front /home/front

WORKDIR /home/front

#RUN yarn install

RUN yarn install && \
    yarn run build && \
    cp -RT build dist; 

CMD yarn start; 
    
