FROM node:12.18.4

WORKDIR /home/api

CMD (which yarn || npm i -g yarn@1.15.2) && \
    if [ "$NODE_ENV" = "production" ] || [ "$NODE_ENV" = "qa" ]; then \
        yarn install --production && \
        yarn run start:production; \
    else \
        yarn install && \
        yarn start; \
    fi
