FROM node:12.18.4

COPY ./api /home/api
WORKDIR /home/api

#RUN apt-get -y install iptables cron

CMD (which yarn || npm i -g yarn@1.15.2) && \
    echo "$NODE_ENV"; \
    yarn install --production=false && \
    if [ "$NODE_ENV" = "production" ] || [ "$NODE_ENV" = "recette" ] || [ "$NODE_ENV" = "test" ]; then \
        yarn build:production && \ 
	    yarn start:production; \
    else \
        yarn start; \
    fi; 
    # Utile pour debugguer et rentrer dans le conteneur si celui-ci n'est plus OK
    #sleep infinity;
