version: "3.3"
services:
  nginx:
    volumes:
      - './nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf'

  api:
    build:
      context: .
      dockerfile: dockerfile_api
    environment:
      - NODE_ENV=development
    volumes:
      - './api:/home/api'
      - './api/src/assets/datas/depuis_datalake_mockdata:/mnt/datalakepe/depuis_datalake'

  front:
    build:
      context: .
      dockerfile: dockerfile_front
    restart: unless-stopped
    expose:
      - '3000'
    environment:
      - TZ=Europe/Paris
    volumes:
      - './front:/home/front'
    networks:
      mobiville_network:
        ipv4_address: 173.0.0.30
    stdin_open: true
    environment:
      - NODE_ENV=development
